version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: cinema_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cinema-net

  redis:
    image: redis:7-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cinema-net

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: cinema_redis_ui
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - cinema-net
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  cinema-net:
    driver: bridge